name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Build with dotnet
      run: dotnet build --configuration Release
      working-directory: Controller
    - uses: actions/upload-artifact@v1
      with:
        name: controller
        path: Controller/bin/Release/netcoreapp3.1
      
